##  -*- python -*-

import glob

env = Environment(CPPPATH=['../..'])
miniswig = env.Program('miniswig/miniswig',
                       ['miniswig/create_docu.cpp',
                        'miniswig/xmlwriter.cpp',
                        'miniswig/create_wrapper.cpp',
                        'miniswig/main.cpp',
                        'miniswig/tree.cpp',
                        'miniswig/parser.yy',
                        'miniswig/lexer.ll'], 
                       CPPPATH=["..", "miniswig"])

Export('miniswig')

# EOF #
