## -*- python -*-

import SCons

Import(['env', 'miniswig'])

env = Environment(MINISWIG='tools/miniswig/miniswig')

env.Command('miniswig.tmp', 'wrapper.interface.hpp',
            ["cpp -x c  -CC $SOURCE -o $TARGET -DSCRIPTING_API"])

env.Depends(env.Command(['wrapper.cpp', 'wrapper.hpp'], 'miniswig.tmp',
                        ["$MINISWIG  --input $SOURCE --output-cpp ${TARGETS[0]} --output-hpp ${TARGETS[1]} --module windstille --select-namespace Scripting"]),
            miniswig)

# EOF #
