/**
 * WARNING: This file is automatically generated from:
 *  'src/scripting/wrapper.interface.hpp'
 * DO NOT CHANGE
 */
#ifndef __windstille_WRAPPER_H__
#define __windstille_WRAPPER_H__

#include "wrapper_util.hpp"

extern WrappedFunction windstille_global_functions[];
extern WrappedClass windstille_classes[];

#endif

