import glob
import os

env = Environment(ENV = os.environ)

def build_tiles(target, source, env):
    print "Building tiles file:", str(target[0])
    f = open(str(target[0]),"w")
    f.write('<resources>\n')
    f.write('  <section name="tiles">\n')
    for i in glob.glob('images/tiles/*.png'):
        f.write('   <sprite name="%s">\n' % os.path.basename(i)[0:-4])
        f.write('     <image file="%s"/>\n' % i)
        f.write('   </sprite>\n')
    f.write('  </section>\n')
    f.write('</resources>\n')
    f.close()

tiles_builder = Command('tiles.xml', ['images/tiles/', 'SConstruct'],
                        build_tiles)

Depends(tiles_builder, glob.glob('images/tiles/*.png'))

# EOF #

